version: "3.8"
services:
  flowise:
    image: flowiseai/flowise
    ports:
      - "3000:3000"
    environment:
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=supersecret
    restart: on-failure:10
